services:
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: pokemon

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080