micronaut.application.name: pokemonapi
datasources:
  default:
    db-type: mariadb
    dialect: MYSQL
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://localhost:3306/pokemon
    username: root
    password: root

liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.yaml


